In [5]:
import pandas

In [6]:
import pandas as pd

In [7]:
pd?

# Introducing Pandas Objects

In [8]:
import numpy as np
import pandas as pd

## The Pandas Series Object

### Series as generalized Numpy array

In [9]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data 
#Series used for manipulating the pattern of data that are kept in an array.

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [10]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [11]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [12]:
data[1]

0.5

In [13]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [14]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [15]:
data['b']

0.5

In [16]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [17]:
data[5]

0.5

### Series as specialized dictionary

In [18]:
population_dict = {'California': 3833521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California     3833521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [19]:
population['California':'Illinois']

California     3833521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

### Constructing Series objects

In [20]:
pd.Series([2, 4, 6]) # Index defaults to an integer sequence

0    2
1    4
2    6
dtype: int64

In [21]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [22]:
pd.Series({2: 'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [23]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

# The Pandas DataFrame Object

### DataFrame as a generalized Numpy array

In [24]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
            'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [25]:
states = pd.DataFrame({'population': population,
                      'area': area})
states

population    area
California     3833521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [26]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [27]:
states.columns

Index(['population', 'area'], dtype='object')

### DataFram as specialized dictionary

In [28]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [29]:
states['population']

California     3833521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: population, dtype: int64

### Constructing DataFrame objects

### From a single Series object

In [30]:
pd.DataFrame(population, columns=['population'])

population
California     3833521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [31]:
pd.DataFrame(population, columns=['area'])

area
California   3833521
Texas       26448193
New York    19651127
Florida     19552860
Illinois    12882135

### From a list of dicts

In [32]:
data = [{'a': i, 'b': 2 * i}
    for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

### From a list of dicts

In [33]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

### From a dictionary of Series objects

In [34]:
pd.DataFrame({'population': population, 'area': area})

population    area
California     3833521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

### From a two-dimensional NumPy array

In [35]:
pd.DataFrame(np.random.rand(3, 2), columns=['foo', 'bar'], index=['a', 'b', 'c'])

foo       bar
a  0.235891  0.060183
b  0.311221  0.902627
c  0.865420  0.316980

### From a Numpy structured array

In [36]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [37]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

## The Pandas Index Object

In [38]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

### Index as immutable array

In [39]:
ind[1]

3

In [40]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [41]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [42]:
ind[1] = 0

TypeError: Index does not support mutable operations

### Index as ordered set

In [44]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [45]:
indA & indB # Intersection

Int64Index([3, 5, 7], dtype='int64')

In [46]:
indA | indB # union

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [47]:
indA ^ indB # symmetric difference Universe - (A & B)

Int64Index([1, 2, 9, 11], dtype='int64')

# Data Indexing and Selection

## Data Selection in Series

### Series as dictionary

In [48]:
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [49]:
data['b']

0.5

In [50]:
'a' in data

True

In [51]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [52]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [53]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

### Series as one-dimensional array

In [54]:
# slicing by explicit index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [55]:
# slicing by implicit index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [56]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [57]:
# fancy indexing
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

### Indexers: loc, iloc, and ix

In [58]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [59]:
# explict index when indexing
data[1]

'a'

In [60]:
# implict index when slicing
data[1:3]

3    b
5    c
dtype: object

In [61]:
data.loc[1]

'a'

In [62]:
data.loc[1:3] # loc allows indexing and slicing that always references the explicit index

1    a
3    b
dtype: object

In [63]:
data.loc[1:5]

1    a
3    b
5    c
dtype: object

In [64]:
data.iloc[1]
'b'

'b'

In [65]:
data.iloc[1:3]

3    b
5    c
dtype: object

In [66]:
data.iloc[:3]

1    a
3    b
5    c
dtype: object

In [67]:
data.iloc[0] # iloc allows indexing and slicing that always references the implicit Python-style index

'a'

## Data Selection in DataFrame

### DataFrame as a dictionary

In [68]:
import pandas as pd
area = pd.Series({'California': 423967, 'Texas': 695662,
                'New York': 141297, 'Florida': 170312,
                'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                'New York': 19651127, 'Florida': 19552860,
                'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'population':pop})
data

area  population
California  423967    38332521
Texas       695662    26448193
New York    141297    19651127
Florida     170312    19552860
Illinois    149995    12882135

In [69]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [70]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [71]:
data.population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: population, dtype: int64

In [72]:
data.area is data['area']

True

In [73]:
# data.pop is data['pop']

In [74]:
data['density'] = data['population'] / data['area']
data

area  population     density
California  423967    38332521   90.413926
Texas       695662    26448193   38.018740
New York    141297    19651127  139.076746
Florida     170312    19552860  114.806121
Illinois    149995    12882135   85.883763

### DataFrame as two-dimensional array

In [75]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [76]:
data.T # Transpose matrix

California         Texas      New York       Florida  \
area        4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05   
population  3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07   
density     9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02   

                Illinois  
area        1.499950e+05  
population  1.288214e+07  
density     8.588376e+01

In [77]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [78]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [79]:
data.iloc[:3, :2]

area  population
California  423967    38332521
Texas       695662    26448193
New York    141297    19651127

In [80]:
data.loc[:'Illinois', :'population']

area  population
California  423967    38332521
Texas       695662    26448193
New York    141297    19651127
Florida     170312    19552860
Illinois    149995    12882135

In [81]:
data.ix[:3, :'population']

/home/thanadon/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


area  population
California  423967    38332521
Texas       695662    26448193
New York    141297    19651127

In [82]:
data.loc[data.density > 100, ['population', 'density']]

population     density
New York    19651127  139.076746
Florida     19552860  114.806121

In [83]:
data.iloc[0, 2] = 90
data

area  population     density
California  423967    38332521   90.000000
Texas       695662    26448193   38.018740
New York    141297    19651127  139.076746
Florida     170312    19552860  114.806121
Illinois    149995    12882135   85.883763

### Additional indexing conventions

In [84]:
data['Florida':'Illinois']

area  population     density
Florida   170312    19552860  114.806121
Illinois  149995    12882135   85.883763

In [85]:
data[1:3]

area  population     density
Texas     695662    26448193   38.018740
New York  141297    19651127  139.076746

In [86]:
data[data.density > 100]

area  population     density
New York  141297    19651127  139.076746
Florida   170312    19552860  114.806121

# Operating on Data in Pandas

## Ufuncs: Index Preservation

In [1]:
import pandas as pd
import numpy as np

In [2]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [3]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                 columns=['A','B','C','D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [4]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [5]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

## UFuncs: Index Alignment

### Index alignment in Series

In [6]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                       'New York': 19651127}, name='population')

In [7]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [8]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [9]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [10]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

### Index alignment in DataFrame

In [11]:
A = pd.DataFrame(rng.randint(0, 20, (2,2)), columns=list('AB'))
A

A   B
0  1  11
1  5   1

In [12]:
B = pd.DataFrame(rng.randint(0, 10, (3,3)), columns=list('BAC'))
B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [13]:
A + B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [14]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

## Ufunc: Operations Between DataFrame and Series

In [16]:
A = rng.randint(10, size=(3,4))
A

array([[1, 9, 8, 9],
       [4, 1, 3, 6],
       [7, 2, 0, 3]])

In [19]:
A - A[0]

array([[ 0,  0,  0,  0],
       [ 3, -8, -5, -3],
       [ 6, -7, -8, -6]])

In [20]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1  3 -8 -5 -3
2  6 -7 -8 -6

In [24]:
print(df)
print(df.iloc[0]) # row at 0

   Q  R  S  T
0  1  9  8  9
1  4  1  3  6
2  7  2  0  3
Q    1
R    9
S    8
T    9
Name: 0, dtype: int64


Q  R  S  T
0  1  9  8  9
1  4  1  3  6
2  7  2  0  3

In [26]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0 -8  0 -1  0
1  3  0  2  5
2  5  0 -2  1

In [29]:
halfrow = df.iloc[0, ::2]
halfrow

Q    1
S    8
Name: 0, dtype: int64

In [28]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1  3.0 NaN -5.0 NaN
2  6.0 NaN -8.0 NaN

# Handling Mission Data

## Trade-Offs in Mission Data Conventions

In [1]:
# Masking approach -> the mask might be an entirely seperate Boolean array
# Sentinel approach -> data-specific convention (-9999, NaN)
# Non of these approach -> use of a seperate mask array requires allocation of an additional Boolean array

## Missing Data in Pandas

In [3]:
# Numpy does have support for masked arrays 
#that have a seperate Boolean mask array attached for marking data
# Pandas chose to use sentinels for missing data, and use two alread-existing Python null values:
# the special floting-point NaN value, and the Python None object

### None: Pythonic missing data

In [1]:
import numpy as np
import pandas as pd

In [2]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [3]:
for dtype in ['object', 'int']:
    print("dtype = ", dtype)
    %timeit np.arange(1E6, dtype=dtype).sum()
    print()

dtype =  object
50.6 ms ± 707 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype =  int
1.53 ms ± 71.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)



In [5]:
#vals1.sum() Error

### NaN: Missing numerical data

In [6]:
vals2 = np.array([1, np.nan, 3, 4])
vals2.dtype

dtype('float64')

In [7]:
1 + np.nan

nan

In [8]:
0 * np.nan

nan

In [9]:
vals2.sum(), vals2.min(), vals2.max()

(nan, nan, nan)

In [10]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2) # Sum all values

(8.0, 1.0, 4.0)

In [11]:
vals2

array([ 1., nan,  3.,  4.])

### NaN and None in Pandas

In [12]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [13]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int64

In [14]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

## Operating on Null Values

### Detecting null values

In [15]:
data = pd.Series([1, np.nan, 'hello', None])

In [16]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [17]:
data[data.notnull()]

0        1
2    hello
dtype: object

### Dropping null values

In [18]:
data.dropna() # Removes NA values

0        1
2    hello
dtype: object

In [19]:
df = pd.DataFrame([[1, np.nan, 2], [2, 3, 5], [np.nan, 4, 6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [20]:
df.dropna(axis='columns') 
# Dropping all columns that contains a null value

2
0  2
1  5
2  6

In [21]:
df[3] = np.nan # Add all NaN values into a column
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [22]:
df.dropna(axis='columns', how='all') 
# Only drop a row or column that are all null values

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [23]:
df.dropna(axis='rows', thresh=3) 
# thresh is a minimum number of non-null values for the rows/column to be kept

0    1  2   3
1  2.0  3.0  5 NaN

### Filling null values

In [24]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [25]:
data.fillna(0) 
# Fill NA entries with a single value such as zero

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [26]:
# forward-fill
data.fillna(method='ffill')
# Specify a forward-fill to propagate the previous value forward

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [27]:
# back-fill
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [28]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [29]:
df.fillna(method='ffill', axis=1)
# Forward-fill along with horizontal axis

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

# Hierarchical Indexing

In [30]:
import pandas as pd
import numpy as np

## A Multiply Indexed Series

### The bad way

In [31]:
index = [('California', 2000), ('California', 2010), 
         ('New York',2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations= [33871648, 37253956,
              18976457, 19378102,
              20851820, 25145561]
pop = pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [32]:
pop[('California', 2010):('Texas', 2000)]

(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
dtype: int64

In [33]:
pop[[i for i in pop.index if i[1] == 2010]]

(California, 2010)    37253956
(New York, 2010)      19378102
(Texas, 2010)         25145561
dtype: int64

### The bettter way: Pandas MultiIndex

In [34]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex(levels=[['California', 'New York', 'Texas'], [2000, 2010]],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [35]:
pop = pop.reindex(index) 
# Reindex our series with this MultiIndex
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [38]:
pop[:, 2010]
# Output only countries that have 2010

California    37253956
New York      19378102
Texas         25145561
dtype: int64

### MultiIndex as extra dimension

In [40]:
pop_df = pop.unstack()
# Convert a multiply indexed series into a indexed DataFrame
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [42]:
pop_df.stack() 
# Convert a indexed DataFrame into a multiply index series

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [46]:
pop_df = pd.DataFrame({'total': pop, 'under18': [9267089, 9284094,
                                                4687374, 4318033,
                                                5906301, 6879014]})
pop_df
# Using MultiIndex to add another column to the DatFrame

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [48]:
f_u18 = pop_df['under18'] / pop_df['total']
f_u18.unstack()

2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

## Methods of MultiIndex Creation

In [49]:
df = pd.DataFrame(np.random.rand(4, 2),
                  index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns=['data1', 'data2'])
df

data1     data2
a 1  0.369090  0.892103
  2  0.588785  0.688655
b 1  0.395862  0.203128
  2  0.102443  0.870212

In [56]:
data = {('California', 2000): 33871648,
        ('California', 2010): 37253956,
        ('Texas', 2000): 20851820,
        ('New York', 2000): 18976457,
        ('New York', 2010): 19378102}
pd.Series(data)

California  2000    33871648
            2010    37253956
Texas       2000    20851820
New York    2000    18976457
            2010    19378102
dtype: int64

### Explicit MultiIndex constructors

In [57]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [61]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)])
# Construct multiIndex and add labels

In [67]:
pd.MultiIndex.from_product([['a', 'b'], [1, 2]])
# Construct multiIndex and add labels 
# but it is using one product instead of repeating 

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [68]:
pd.MultiIndex(levels=[['a', 'b'], [1, 2]],
              labels=[[0, 0, 1, 1], [0, 1, 0 ,1]])
# Construct MultiIndex directly

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

### MultiIndex level names

In [70]:
pop.index.names = ['state', 'year']
pop
# Setting the names attribute of the index after the fact

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

### MultiIndex for columns

In [74]:
# hierarchical indices and columns
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                   names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
                                     names=['subject', 'type'])
# mock some data
data = np.round(np.random.randn(4, 6) , 1)
data[:, :: 2] *= 10
data += 37
# create the DataFrame
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      35.0  35.7  38.0  36.2  54.0  37.0
     2      45.0  37.4  29.0  37.6  34.0  38.8
2014 1      29.0  35.7  28.0  37.1  25.0  37.6
     2      27.0  37.2  49.0  38.1  28.0  36.9

In [75]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      38.0  36.2
     2      29.0  37.6
2014 1      28.0  37.1
     2      49.0  38.1

## Indexing and Slicing a MultiIndex

### Multiply indexed Series

In [76]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [78]:
pop['California', 2000]
# indexing with multiple terms

33871648

In [80]:
pop['California']
# Partial indexing (one of the levels in the index)

year
2000    33871648
2010    37253956
dtype: int64

In [81]:
pop.loc['California':'New York']

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
dtype: int64

In [82]:
pop[:, 2000]

state
California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [85]:
pop[pop > 22000000]

state       year
California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64

In [86]:
pop[['California', 'Texas']]

state       year
California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
dtype: int64

### Multiply indexed DataFrames

In [87]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      35.0  35.7  38.0  36.2  54.0  37.0
     2      45.0  37.4  29.0  37.6  34.0  38.8
2014 1      29.0  35.7  28.0  37.1  25.0  37.6
     2      27.0  37.2  49.0  38.1  28.0  36.9

In [88]:
health_data['Guido', 'HR']

year  visit
2013  1        38.0
      2        29.0
2014  1        28.0
      2        49.0
Name: (Guido, HR), dtype: float64

In [89]:
health_data.iloc[:2, :2]

subject      Bob      
type          HR  Temp
year visit            
2013 1      35.0  35.7
     2      45.0  37.4

In [90]:
health_data.loc[:, ('Bob', 'HR')]

year  visit
2013  1        35.0
      2        45.0
2014  1        29.0
      2        27.0
Name: (Bob, HR), dtype: float64

In [91]:
health_data.loc[(:, 1), (:, 'HR')]

SyntaxError: invalid syntax (<ipython-input-91-fb34fa30ac09>, line 1)

## Rearranging Multi-Indices

### Sorted and unsorted indices

In [95]:
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]])
# Cartesian
data = pd.Series(np.random.rand(6), index=index)
data.index.names = ['char', 'int']
# Setting index names
data

char  int
a     1      0.897293
      2      0.507053
c     1      0.689113
      2      0.054094
b     1      0.054545
      2      0.030532
dtype: float64

In [99]:
try:
    data['a':'b']
except keyError as e:
    print(type(e))
    print(e)

NameError: name 'keyError' is not defined

In [100]:
data = data.sort_index()
data

char  int
a     1      0.897293
      2      0.507053
b     1      0.054545
      2      0.030532
c     1      0.689113
      2      0.054094
dtype: float64

In [101]:
try:
    data['a':'b']
except KeyError as e:
    print(type(e))
    print(e)

In [102]:
data['a':'b']

char  int
a     1      0.897293
      2      0.507053
b     1      0.054545
      2      0.030532
dtype: float64

### Stacking and unstacking indices

In [103]:
pop.unstack(level=0)

state  California  New York     Texas
year                                 
2000     33871648  18976457  20851820
2010     37253956  19378102  25145561

In [104]:
pop.unstack(level=1)

year            2000      2010
state                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [105]:
pop.unstack().stack()

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

### Index setting and resetting

In [106]:
pop_flat = pop.reset_index(name='population')
# setting index of population colunm
pop_flat

state  year  population
0  California  2000    33871648
1  California  2010    37253956
2    New York  2000    18976457
3    New York  2010    19378102
4       Texas  2000    20851820
5       Texas  2010    25145561

In [107]:
pop_flat.set_index(['state', 'year'])

population
state      year            
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561

## Data Aggregations on Multi-Indices

In [108]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      35.0  35.7  38.0  36.2  54.0  37.0
     2      45.0  37.4  29.0  37.6  34.0  38.8
2014 1      29.0  35.7  28.0  37.1  25.0  37.6
     2      27.0  37.2  49.0  38.1  28.0  36.9

In [110]:
data_mean = health_data.mean(level='year')
# Average between visit 1 and 2 in each year and merge to one row
data_mean

subject   Bob        Guido         Sue       
type       HR   Temp    HR  Temp    HR   Temp
year                                         
2013     40.0  36.55  33.5  36.9  44.0  37.90
2014     28.0  36.45  38.5  37.6  26.5  37.25

In [111]:
data_mean.mean(axis=1, level='type')

type         HR       Temp
year                      
2013  39.166667  37.116667
2014  31.000000  37.100000

## Combining Datasets: Concat and Append

In [112]:
import pandas as pd
import numpy as np

In [116]:
def make_df(cols, ind):
    """Quickly make a DataFrame"""
    data = {c: [str(c) + str(i) for i in ind]
           for c in cols}
    return pd.DataFrame(data, ind)

# Example DataFrame
make_df('ABC', range(3))
    

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

### Recall: Concatenation of NumPy Arrays

In [117]:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
x = [[1, 2], [3, 4]]
np.concatenate([x, x], axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [121]:
np.concatenate([x, x], axis=0)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

### Simple Concetenation with pd.concat

In [128]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])
pd.concat([ser1, ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [130]:
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])
print(df1);
print(df2);
print(pd.concat([df1, df2]))

    A   B
1  A1  B1
2  A2  B2
    A   B
3  A3  B3
4  A4  B4
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


In [133]:
df3 = make_df('CD', [0, 1])
df4 = make_df('CD', [0, 1])
print(df3);
print(df4);
print(pd.concat([df3, df4], axis=1))

    C   D
0  C0  D0
1  C1  D1
    C   D
0  C0  D0
1  C1  D1
    C   D   C   D
0  C0  D0  C0  D0
1  C1  D1  C1  D1


### Duplicate indices

In [135]:
x = make_df('AB', [0, 1])
y = make_df('AB', [2, 3])
y.index = x.index # make duplicate indices!
print(x)
print(y)
print(pd.concat([x, y]))

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A2  B2
1  A3  B3
    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3


### catching the repeats as an error

In [158]:
try:
    pd.concat([x, y], verify_integrity=True)
    # Index from both DataFrames are overlapped
except ValueError as e:
        print("ValueError:", e)

ValueError: Indexes have overlapping values: Int64Index([0, 1], dtype='int64')


### Ignoring the index

In [160]:
print(x)
print(y)
print(pd.concat([x, y], ignore_index=True))
# The concatenation will create a new integer index for the resulting Series

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A2  B2
1  A3  B3
    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3


### Adding MultiIndex keys

In [161]:
print(x)
print(y)
print(pd.concat([x, y], keys=['x', 'y']))
# x index for DataFrame named x
# y index for DataFrame named y

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A2  B2
1  A3  B3
      A   B
x 0  A0  B0
  1  A1  B1
y 0  A2  B2
  1  A3  B3


### Concatenation with joins

In [163]:
df5 = make_df('ABC', [1, 2])
df6 = make_df('BCD', [3, 4])
print(df5)
print(df6)
print(pd.concat([df5, df6]))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4


/home/thanadon/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """


In [165]:
print(df5)
print(df6)
print(pd.concat([df5, df6], join='inner'))
# inner for intersection
# outer for union

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4


In [168]:
print(df5)
print(df6)
print(pd.concat([df5, df6], join_axes=[df5.columns]))
# Specifying the index of the remaining colunms
# let the column contains NaN

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
     A   B   C
1   A1  B1  C1
2   A2  B2  C2
3  NaN  B3  C3
4  NaN  B4  C4


### The append() method

In [173]:
print(df1)
print(df2)
print(df1.append(df2))
# like df1.concat([df1, df2]) but df1.concat() is better
# because df1.append() creates a new object with the combined data.
# And involves creation of a new index and data buffer.

    A   B
1  A1  B1
2  A2  B2
    A   B
3  A3  B3
4  A4  B4
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


In [171]:
print(df5)
print(df6)
print(df5.append(df6))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4


/home/thanadon/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)


## Combining Datasets: Merge and Join